#!/usr/bin/env python3
"""Compress approved OPEN-letter-OPEN JSON plans into 1 kHz C keyframes."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


LETTERS = "ABCDEFGHIKLMNOPQRSTUVWXY"
JOINT_COUNT = 20
Q12_SCALE = 1 << 12
TICK_HZ = 1000
CLASS_ID = {letter: ord(letter) - ord("A") + 1 for letter in LETTERS}
PHASE_ENUM = {
    "release_thumb": "ASL_PHASE_RELEASE_THUMB",
    "prepare_release_crossing": "ASL_PHASE_PREPARE_RELEASE_CROSSING",
    "release_finger_spread": "ASL_PHASE_RELEASE_FINGER_SPREAD",
    "release_non_thumb": "ASL_PHASE_RELEASE_NON_THUMB",
    "retract_thumb": "ASL_PHASE_RETRACT_THUMB",
    "form_non_thumb_shape": "ASL_PHASE_FORM_NON_THUMB_SHAPE",
    "set_finger_spread": "ASL_PHASE_SET_FINGER_SPREAD",
    "settle_crossing": "ASL_PHASE_SETTLE_CROSSING",
    "position_thumb": "ASL_PHASE_POSITION_THUMB",
    "target_hold": "ASL_PHASE_TARGET_HOLD",
}


def q12(value: float) -> int:
    result = round(value * Q12_SCALE)
    if not -32768 <= result <= 32767:
        raise ValueError(f"Q4.12 overflow: {value}")
    return result


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as stream:
        return json.load(stream)


def contiguous_phase_endpoints(points: list[dict[str, Any]]) -> list[dict[str, Any]]:
    endpoints: list[dict[str, Any]] = []
    for point in points:
        if point["phase"] == "measured_start":
            continue
        if endpoints and endpoints[-1]["phase"] == point["phase"]:
            endpoints[-1] = point
        else:
            endpoints.append(point)
    return endpoints


def validate_plan(
    source_dir: Path, letter: str
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    plan_path = source_dir / f"trajectory_{letter}.json"
    report_path = source_dir / f"trajectory_{letter}_collision_report.json"
    plan = load_json(plan_path)
    report = load_json(report_path)

    if plan.get("text") != letter:
        raise ValueError(f"{plan_path}: text is not {letter}")
    if report.get("plan_id") != plan.get("plan_id"):
        raise ValueError(f"{letter}: collision report plan_id mismatch")
    if report.get("approved") is not True:
        raise ValueError(f"{letter}: collision report is not approved")
    if report.get("unexpected_collision_sample_count") != 0:
        raise ValueError(f"{letter}: unexpected collisions are not zero")
    points = plan.get("points", [])
    if not points or len(points[0].get("q_rad", [])) != JOINT_COUNT:
        raise ValueError(f"{letter}: invalid joint data")
    if any(abs(value) > 1e-12 for value in points[0]["q_rad"]):
        raise ValueError(f"{letter}: plan does not begin at OPEN")
    if any(abs(value) > 1e-12 for value in points[-1]["q_rad"]):
        raise ValueError(f"{letter}: plan does not finish at OPEN")

    endpoints = contiguous_phase_endpoints(points)
    if not endpoints or not any(p["phase"] == "target_hold" for p in endpoints):
        raise ValueError(f"{letter}: target_hold keyframe is missing")
    for endpoint in endpoints:
        if endpoint["phase"] not in PHASE_ENUM:
            raise ValueError(f"{letter}: unknown phase {endpoint['phase']}")
    return plan, endpoints


def render_header(action_count: int) -> str:
    return f"""#ifndef ASL_ACTIONS_GENERATED_H
#define ASL_ACTIONS_GENERATED_H

#include <stddef.h>
#include <stdint.h>

#include \"asl_motion.h\"

#define ASL_GENERATED_TICK_HZ {TICK_HZ}u
#define ASL_GENERATED_ACTION_COUNT {action_count}u

extern const uint8_t asl_generated_source_class_map[ASL_SOURCE_CLASS_COUNT];
extern const asl_keyframe_t asl_generated_keyframes[];
extern const size_t asl_generated_keyframe_count;
extern const asl_action_descriptor_t
    asl_generated_actions[ASL_GENERATED_ACTION_COUNT];

#endif
"""


def render_source(source_dir: Path) -> str:
    lines = [
        "/* Generated by tools/export_asl_actions.py; do not hand-edit. */",
        f"/* Source: {source_dir.name}/trajectory_<letter>.json */",
        '#include "asl_actions_generated.h"',
        "",
        "const uint8_t asl_generated_source_class_map[ASL_SOURCE_CLASS_COUNT] = {",
        "    " + ", ".join(f"ASL_CLASS_{letter}" for letter in LETTERS),
        "};",
        "",
        "const asl_keyframe_t asl_generated_keyframes[] = {",
    ]
    descriptors: list[tuple[str, str, int, int, int]] = []
    first_keyframe = 0

    for letter in LETTERS:
        plan, endpoints = validate_plan(source_dir, letter)
        previous_time = 0.0
        total_ticks = 0
        lines.append(f"    /* {letter}: plan_id {plan['plan_id']} */")
        for endpoint_index, endpoint in enumerate(endpoints):
            end_time = float(endpoint["time_from_start_s"])
            duration_ticks = round((end_time - previous_time) * TICK_HZ)
            if not 1 <= duration_ticks <= 65535:
                raise ValueError(
                    f"{letter}/{endpoint['phase']}: invalid duration {duration_ticks}"
                )
            previous_time = end_time
            total_ticks += duration_ticks
            flags = []
            if endpoint["phase"] == "target_hold":
                flags.append("ASL_KEYFRAME_FLAG_HOLD")
            if endpoint_index + 1 == len(endpoints):
                flags.append("ASL_KEYFRAME_FLAG_ACTION_END")
            flag_text = " | ".join(flags) if flags else "0u"
            values = ", ".join(str(q12(value)) for value in endpoint["q_rad"])
            lines.extend(
                [
                    "    {",
                    f"        {duration_ticks}u, {PHASE_ENUM[endpoint['phase']]}, {flag_text},",
                    f"        {{ {values} }}",
                    "    },",
                ]
            )
        descriptors.append(
            (letter, plan["plan_id"], first_keyframe, len(endpoints), total_ticks)
        )
        first_keyframe += len(endpoints)

    lines.extend(
        [
            "};",
            "",
            "const size_t asl_generated_keyframe_count =",
            "    sizeof(asl_generated_keyframes) / sizeof(asl_generated_keyframes[0]);",
            "",
            "const asl_action_descriptor_t",
            "    asl_generated_actions[ASL_GENERATED_ACTION_COUNT] = {",
        ]
    )
    for letter, plan_id, first, count, total in descriptors:
        lines.extend(
            [
                "    {",
                f'        "{plan_id}", {first}u, {total}u, {count}u,',
                f"        ASL_CLASS_{letter}, '{letter}', 1u",
                "    },",
            ]
        )
    lines.extend(["};", ""])
    return "\n".join(lines)


def main() -> None:
    workspace = Path(__file__).resolve().parents[3]
    default_source = workspace / "SW" / "hx5_asl_fingerspelling" / "generated"
    default_output = Path(__file__).resolve().parents[1] / "generated"
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=default_source)
    parser.add_argument("--output", type=Path, default=default_output)
    args = parser.parse_args()

    args.output.mkdir(parents=True, exist_ok=True)
    (args.output / "asl_actions_generated.h").write_text(
        render_header(len(LETTERS)), encoding="utf-8"
    )
    (args.output / "asl_actions_generated.c").write_text(
        render_source(args.source), encoding="utf-8"
    )
    print(f"exported {len(LETTERS)} approved actions to {args.output}")


if __name__ == "__main__":
    main()
