#ifndef ASL_SOC_MMIO_H
#define ASL_SOC_MMIO_H

#include <stdint.h>
#include "asl_soc_config.h"

#define ASL_IRQ_ID_OFFSET            UINT32_C(0x000)
#define ASL_IRQ_INFO_OFFSET          UINT32_C(0x004)
#define ASL_IRQ_PENDING_OFFSET       UINT32_C(0x008)
#define ASL_IRQ_ENABLE_OFFSET        UINT32_C(0x00C)
#define ASL_IRQ_EDGE_OFFSET          UINT32_C(0x010)
#define ASL_IRQ_RAW_OFFSET           UINT32_C(0x014)
#define ASL_IRQ_THRESHOLD_OFFSET     UINT32_C(0x018)
#define ASL_IRQ_CLAIM_OFFSET         UINT32_C(0x01C)
#define ASL_IRQ_PRIORITY_BASE_OFFSET UINT32_C(0x020)
#define ASL_IRQ_PENDING_SET_OFFSET   UINT32_C(0x040)
#define ASL_IRQ_PENDING_CLEAR_OFFSET UINT32_C(0x044)
#define ASL_IRQ_IN_SERVICE_OFFSET    UINT32_C(0x048)

#define ASL_IRQ_SOURCE_ETHERNET      1u
#define ASL_IRQ_SOURCE_CNN           2u
#define ASL_IRQ_SOURCE_PROTOCOL      3u
#define ASL_IRQ_SOURCE_HOST_UART     4u
#define ASL_IRQ_SOURCE_WATCHDOG      5u
#define ASL_IRQ_SOURCE_SAFETY        6u
#define ASL_IRQ_SOURCE_POSE_PROTOCOL 7u
#define ASL_IRQ_SOURCE_ETH_ERROR     8u

#define ASL_CNN_CONTROL_OFFSET       UINT32_C(0x000)
#define ASL_CNN_STATUS_OFFSET        UINT32_C(0x004)
#define ASL_CNN_INPUT_ADDRESS_OFFSET UINT32_C(0x008)
#define ASL_CNN_INPUT_BYTES_OFFSET   UINT32_C(0x00C)
#define ASL_CNN_INPUT_CHECKSUM_OFFSET UINT32_C(0x010)
#define ASL_CNN_CLASS_CONFIG_OFFSET  UINT32_C(0x014)
#define ASL_CNN_RESULT_OFFSET        UINT32_C(0x018)
#define ASL_CNN_SEQUENCE_OFFSET      UINT32_C(0x01C)
#define ASL_CNN_DMA_CHECKSUM_OFFSET  UINT32_C(0x020)
#define ASL_CNN_DMA_BYTES_READ_OFFSET UINT32_C(0x024)

#define ASL_CNN_CONTROL_START        (UINT32_C(1) << 0)
#define ASL_CNN_CONTROL_AUTO_START   (UINT32_C(1) << 1)
#define ASL_CNN_CONTROL_CLEAR_IRQ    (UINT32_C(1) << 2)
#define ASL_CNN_STATUS_BUSY          (UINT32_C(1) << 1)
#define ASL_CNN_STATUS_DONE          (UINT32_C(1) << 2)
#define ASL_CNN_STATUS_ERROR         (UINT32_C(1) << 3)
#define ASL_CNN_STATUS_IRQ           (UINT32_C(1) << 4)
#define ASL_CNN_CLASS_FORCE          (UINT32_C(1) << 31)
#define ASL_CNN_CLASS_CONFIDENCE_SHIFT 8u

#define ASL_ETH_STATUS_OFFSET        UINT32_C(0x000)
#define ASL_ETH_BUFFER_BASE_OFFSET   UINT32_C(0x004)
#define ASL_ETH_MAX_BYTES_OFFSET     UINT32_C(0x008)
#define ASL_ETH_FRAME_BYTES_OFFSET   UINT32_C(0x00C)
#define ASL_ETH_CHECKSUM_OFFSET      UINT32_C(0x010)
#define ASL_ETH_SEQUENCE_OFFSET      UINT32_C(0x014)
#define ASL_ETH_STATUS_DONE          (UINT32_C(1) << 0)
#define ASL_ETH_STATUS_ERROR         (UINT32_C(1) << 1)
#define ASL_ETH_STATUS_BUFFER_HELD   (UINT32_C(1) << 2)

#define ASL_TIMER_MTIMECMP_LO_OFFSET UINT32_C(0x000)
#define ASL_TIMER_MTIMECMP_HI_OFFSET UINT32_C(0x004)
#define ASL_TIMER_MTIME_LO_OFFSET    UINT32_C(0x008)
#define ASL_TIMER_MTIME_HI_OFFSET    UINT32_C(0x00C)

#define ASL_POSE_CONTROL_OFFSET      UINT32_C(0x000)
#define ASL_POSE_STATUS_OFFSET       UINT32_C(0x004)
#define ASL_POSE_CLASS_OFFSET        UINT32_C(0x008)
#define ASL_POSE_MAX_STEP_OFFSET     UINT32_C(0x00C)
#define ASL_POSE_SEQUENCE_OFFSET     UINT32_C(0x010)
#define ASL_POSE_PROTOCOL_STATUS_OFFSET UINT32_C(0x014)
#define ASL_POSE_PROTOCOL_SEQUENCE_OFFSET UINT32_C(0x018)
#define ASL_POSE_HAND_ID_OFFSET      UINT32_C(0x01C)
#define ASL_POSE_CONTROL_APPLY       (UINT32_C(1) << 0)
#define ASL_POSE_PROTOCOL_PRESENT    (UINT32_C(1) << 0)
#define ASL_POSE_PROTOCOL_BUSY       (UINT32_C(1) << 1)
#define ASL_POSE_PROTOCOL_ERROR      (UINT32_C(1) << 2)
#define ASL_POSE_PROTOCOL_BANK       (UINT32_C(1) << 3)

#define ASL_SAFETY_STATUS_OFFSET     UINT32_C(0x000)
#define ASL_SAFETY_CONTROL_OFFSET    UINT32_C(0x004)
#define ASL_SAFETY_TORQUE_REQUEST    (UINT32_C(1) << 0)
#define ASL_SAFETY_WATCHDOG_ENABLE   (UINT32_C(1) << 1)
#define ASL_SAFETY_WATCHDOG_KICK     (UINT32_C(1) << 2)
#define ASL_SAFETY_CLEAR_FAULT       (UINT32_C(1) << 3)

#define ASL_UART_ID_OFFSET           UINT32_C(0x000)
#define ASL_UART_STATUS_OFFSET       UINT32_C(0x004)
#define ASL_UART_TX_DATA_OFFSET      UINT32_C(0x008)
#define ASL_UART_RX_DATA_OFFSET      UINT32_C(0x00C)
#define ASL_UART_DIVISOR_OFFSET      UINT32_C(0x010)
#define ASL_UART_IRQ_ENABLE_OFFSET   UINT32_C(0x014)
#define ASL_UART_IRQ_STATUS_OFFSET   UINT32_C(0x018)
#define ASL_UART_STATUS_TX_READY     (UINT32_C(1) << 0)
#define ASL_UART_STATUS_TX_BUSY      (UINT32_C(1) << 1)
#define ASL_UART_STATUS_RX_VALID     (UINT32_C(1) << 2)
#define ASL_UART_STATUS_FRAMING_ERR  (UINT32_C(1) << 3)
#define ASL_UART_STATUS_OVERRUN_ERR  (UINT32_C(1) << 4)
#define ASL_UART_STATUS_IRQ          (UINT32_C(1) << 5)
#define ASL_UART_IRQ_TX_DONE         (UINT32_C(1) << 0)
#define ASL_UART_IRQ_RX_VALID        (UINT32_C(1) << 1)
#define ASL_UART_IRQ_ERROR           (UINT32_C(1) << 2)

static inline volatile uint32_t *asl_mmio_register(
    uint32_t base,
    uint32_t offset
) {
    return (volatile uint32_t *)(uintptr_t)(base + offset);
}

#endif
